#!/bin/bash

  for dir in `find . -name ".git" | awk '{len = length($1)} {val = substr($1,1,len-4)}{print val}'`; do
        pushd $dir
        git svn fetch
        git svn rebase
        popd
  done
